[project]
name = "pyadintool"
readme = "README.md"
license-files = ["LICENSE"]
version = "1.0"
classifiers = [
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",	
]
requires-python = ">=3.10"
dependencies = [
  "torch",
  "torchaudio",
  "torchcodec",
  "numpy",
  "pyyaml",
  "sounddevice",
  "huggingface_hub",
  "safetensors"
]

[project.scripts]
pyadintool = "pyadin:app_pyadintool"
pyadinauxtool = "pyadin:app_auxtool"

[tool.setuptools.packages.find]
include = ["pyadin"]

[project.optional-dependencies]
gui = ["pyqtgraph", "PySide6"]

#[[tool.uv.index]]
#name = "pytorch-cpu"
#url = "https://download.pytorch.org/whl/cpu"
#explicit = true

#[tool.uv.sources]
#torch = { index = "pytorch-cpu" }
#torchaudio = { index = "pytorch-cpu" }
